language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '7'
  - '6'
before_script:
script:
  - npm run prepublishOnly
branches:
  except:
    - /^v\d+\.\d+\.\d+$/